### ISSUE TITLE
Progress KCD Utrecht website

### ISSUE THREAD

**Issue by Camphul** [cloudnative-amsterdam/kcd-utrecht-website#1]
# KCD Utrecht Website Progress

The following tasks have to be completed:

- [x] Refactor Zurich references to Utrecht (see #2 )
- [ ] Link to KCD Utrecht youtube
- [x] Link to ticketing
- [X] Socials in footer
- [X] Correct venue 
- [x] Correct date
- [x] Branding (logos etc...)
- [ ] Update privacy policy
- [x] Replace branding with Utrecht branding (when artwork is ready)
- [x] Update e-mail to KCD Utrecht email (updated to ams email for now)
- [X] Update sponsors
- [X] Update media partners
- [ ] Update podcast (remove reference to page/podcasts until more is known)
- [ ] Remove archive data and make ready for KCD Utrecht archive
- [x] Cleanup scheduling until schedule is known
- [X] Mission statement
- [x] Team page
- [x] Add CFP link to homepage

**Artwork / branding tasks**

- [x] Top left navigation logo
- [x] Social preview
- [x] Homepage
- [x] Favicon

Please reply to this issue if there are tasks missing and/or reference other issues/pull requests to update the progress.

**Comment by Camphul** [comment]
Started with simple refactor to Utrecht. See #2

**Comment by rgunaseknokia** [comment]
i am starting with updating the sponsors/media partners and podcast in the code!

**Comment by Camphul** [comment]
I will be doing the team page and adding a link to the CFP site later today.

**Comment by Camphul** [comment]
Moved sponsor component used in archive page to shared component dir, imported shared sponsor component into homepage and deleted homepage sponsor component (didnt include logos see #17 )

**Comment by Camphul** [comment]
Every merged pull request to main branch will be attempted to deploy (as long as build succeeds). See #13 and #14

**Comment by rgunaseknokia** [comment]
To Followup on Monday:

- Follow up with Alessandro for Tickets URL —> src/constants/links.js
- Domain name: Gatsby.yaml
- Logo: sponsors.jsx
- Update archive: Clean it up / Remove existing data  from Zurich / Prepare the archive for KCD Utrecht
- Podcast page: src/components/podcast.jsx

**Comment by Camphul** [comment]
GH pages domain has been configured by Alessandro, received ticket url as well so these items are done.

**Comment by Camphul** [comment]
Event is nearly a year ago, should maybe put in some sort of redirect to the CNCF community page. Closing issue for now :)
